:backend: revealjs
:customcss: common.css

== Terraform как способ инициализации.

=== !
----
resource "digitalocean_kubernetes_cluster" "melbet2" {
  name    = "melbet"
  region  = "lon1"
  version = "1.14.2-do.0"

  node_pool {
    name       = "puppetheatre-pool"
    size       = "s-4vcpu-8gb"
    node_count = 10
    tags       = ["puppetheatre"]
  }

}
----
Итого:: 144 строки для DigitalOcean

=== !
----
resource "google_container_cluster" "melbet" {
  name               = "melbet-cluster"
  location               = "europe-north1-a"
  remove_default_node_pool = true
  initial_node_count = 1

  // Use legacy ABAC until these issues are resolved: 
  //   https://github.com/mcuadros/terraform-provider-helm/issues/56
  //   https://github.com/terraform-providers/terraform-provider-kubernetes/pull/73
  enable_legacy_abac = true

  // Wait for the GCE LB controller to cleanup the resources.
  provisioner "local-exec" {
    when    = "destroy"
    command = "sleep 90"
  }
}
----
Итого:: 149 строк для GCP

== Helm как способ управления инфраструктурой

=== Было: 15 строк кода для одного сервиса со скалированием
----
variable "eps_names" { default = ["epsilon400.example.com", 
                                  "epsilon401.example.com", 
                                  "epsilon402.example.com", 
                                  "epsilon403.example.com", 
                                  "epsilon404.example.com",
                                  "epsilon405.example.com"] }

resource "digitalocean_droplet" "epsilon" {
    count = "5"
    image = "ubuntu-16-04-x64"
    name = "${element(var.eps_names, count.index)}"
    region = "lon1"
    size = "s-2vcpu-2gb"
    ssh_keys = ["${var.ssh_fingerprint}"]
    user_data = "${file("minimal.conf")}"
}
----

=== Стало: ручное скалирование сервиса одной строкой
----
service_3:
  image: artifactory.example.com/docker/service_3
    tag: 1.0.5
  replicaCount: 8
----
[%step]
*Для управления числом под достаточно указать replicaCount.

=== Стало: автоматическое скалирование сервиса одним template
----
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
...
----
[%step]
*Штатные возможности Kubernetes легко автоматизируются в Helm.

=== Было: 7 строк кода ради одной записи, прибитой гвоздями
----
resource "digitalocean_record" "example-com-dev" {
  domain = "${digitalocean_domain.example-com.name}"
  type   = "A"
  ttl    = "1800"
  name   = "dev"
  value  = "37.228.89.82"
}
----

=== Стало: автоматизация ingress
----
nginx-ingress:
    service:
      annotations: 
        external-dns.alpha.kubernetes.io/hostname: service_3.example.com, grafana.example.com, kibana.example.com
----
[%step]
*Сервисы пробрасываются одним списком.

=== Стало: автоматизация dns
----
external-dns:
  sources:
    - service
  publishInternalServices: true
  registry: noop
----
[%step]
*Каждый проброшенный сервис получает dns-запись

=== Здесь должен быть код для cert-manager

=== Здесь должен быть код для cluster-autoscaler

== Проблемы

=== Helm tiller
[%step]
* Скоро станет неактуальным
* https://habr.com/ru/company/oleg-bunin/blog/462665 - статья по безопасности Helm

=== Persistence
[%step]
* Неактуальным не станет

=== Kafka
[%step]
* Купить сервис и забыть
