:backend: revealjs
:revealjs_theme: white
:revealjs_customtheme: white_course.css
:revealjs_history:
:customcss: common.css
:revealjs_transition: none
:revealjs_slideNumber: true
:revealjs_center: false
:revealjs_width: 1600
:revealjs_height: 900

== Helm как способ управления инфраструктурой

=== Какие есть инструменты?
[%step]
* Cluster-autoscaler
* Cluster-overprovisioner
* External-dns
* Cert-manager
* Nginx-ingress

== Cluster-autoscaler
[%step]
* Manages autoscaling groups
* AWS, GCE, Azure AKS
* Autodiscovery by ASG tags
* Manually specify ASG(aws only!)

=== Cluster-autoscaler - IAM permissions
----
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}
----

=== Cluster-autoscaler - values.yml
----
cluster-autoscaler:
  autoscalingGroups:
    - name: asg1
      maxSize: 1
      minSize: 10
  awsRegion: 
----
[%step]
* Можно организовать autoDiscovery, но придется тогда создавать asg через терраформ.

== Cluster-overprovisioner
[%step]
* Holds resources for service pods
* HOT autoscaling
* Low PriorityClass

=== Cluster-overprovisioner
----
helm install stable/cluster-overprovisioner
----

== External-dns
[%step]
* Make services discoverable
* AWS Route 53, GC DNS stable
* AWS SD, AzureDNS, CloudFlare beta
* 15+ DNS alpha 

=== External-dns IAM Permissions
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "route53:ListHostedZones",
        "route53:ListResourceRecordSets",
        "route53:ChangeResourceRecordSets"
      ],
      "Resource": "*"
    }
  ]
}
----
[%step]
* Можно отталкиваться от минимальных прав,
создавая hosted-zone через terraform.

=== External-dns nginx-ingress values.yaml
----
controller:
    ingressClass: elb
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: service1.example.com, service2.example.com
----

== Cert-manager
[%step]
* Provision and manage TLS certificates
* Issuers
** CA
** Self-Signed
** ACME
** Vault
** Venafi

== Nginx-ingress
[%step]
* Load-balancing by Kubernetes API
* Providers
** AWS ELB
** DO
** Google Cloud
* Has default-backend

=== Chart annotations for ingress:
----
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.genestack.net
    annotations:
      kubernetes.io/ingress.class: elb
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/issuer: letsencrypt-staging
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.genestack.net
----

== Terraform как способ инициализации.

[.notes]
--
Имприматура - термин, используемый в живописи: цветная тонировка поверхности уже готового белого грунта.
--


=== В Terraform остаются:
[%step]
* Заказ кластера и node-pool/ASG (единственное, что теперь зависит от провайдера)
* Secrets для Kubernetes(credentials для Artifactory)
* Инициализация Helm-tiller
* Первичная установка Helm-chart c указанием namespaces

=== !
----
resource "digitalocean_kubernetes_cluster" "melbet2" {
  name    = "melbet"
  region  = "lon1"
  version = "1.14.2-do.0"

  node_pool {
    name       = "puppetheatre-pool"
    size       = "s-4vcpu-8gb"
    node_count = 10
    tags       = ["puppetheatre"]
  }

}
----
Итого:: 144 строки для DigitalOcean

=== !
----
resource "google_container_cluster" "melbet" {
  name               = "melbet-cluster"
  location               = "europe-north1-a"
  remove_default_node_pool = true
  initial_node_count = 1
  enable_legacy_abac = true
  provisioner "local-exec" {
    when    = "destroy"
    command = "sleep 90"
  }
}
----
Итого:: 144 строки для GCP

=== При переезде из DO в GCP меняется ~20 строк

== Проблемы

=== Helm tiller
[%step]
* Всегда неприятно иметь cluster-admin на своём кластере
* Можно поднимать локально, тогда будет пользоваться вашими правами
* https://habr.com/ru/company/oleg-bunin/blog/462665 - статья по безопасности Helm, которая может слегка смягчить боль

=== Persistence
[%step]
* Создать persistent-volume - полдела.
* Восстановиться из него после падения - почти невыполнимая задача.
* Неактуальным не станет

=== Kafka
[%step]
* Оригинальный helm-chart от Confluent - требует квалификации для варения.
* Современные библиотеки клиентов - с трудом это переживают.
* Купить сервис и забыть.
