---
branches:
  only:
    - master

sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - mkdir output
  - cp -r images output
  - > 
    docker run -v $TRAVIS_BUILD_DIR/:/documents/
    --name asciidoc-to-html 
    asciidoctor/docker-asciidoctor
    asciidoctor-revealjs
    -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0
    -o index.html
    -D /documents/output
    all_in_one.adoc

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output
  on:
    branch: master  
