---
branches:
  only:
    - master

sudo: required

services:
  - docker


cache:
  directories:
    - node_modules

before_install:
  - npm install decktape
  
  - mkdir -p output
  - docker pull dmeatriy1993/asciidoctor_sans
  - git clone -b 3.7.0 --depth 1 https://github.com/hakimel/reveal.js.git output/reveal.js

script:
  - cp white_course.css output/white_course.css
  - cp -r images output
  - cp -r font-awesome-4.7.0 output
  - cp -r roboto-2014 output
  - > 
    docker run -v $TRAVIS_BUILD_DIR/:/documents/
    --name asciidoc-to-html 
    dmeatriy1993/asciidoctor_sans
    asciidoctor-revealjs
    -a revealjsdir=reveal.js
    -r asciidoctor-diagram
    -o index.html
    -D /documents/output
    all_in_one.adoc
  - node node_modules/decktape/decktape.js -s 3200x1800 --slides 1-500 reveal "file:///${TRAVIS_BUILD_DIR}/output/index.html?fragments=true" output/slides.pdf

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output
  on:
    branch: master  
