---
branches:
  only:
    - master

sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor
  - git clone -b 3.7.0 --depth 1 https://github.com/hakimel/reveal.js.git output/reveal.js

script:
  - cp -r images output
  - cp -r font-awesome-4.7.0 output
  - cp -r roboto-2014 output
  - > 
    docker run -v $TRAVIS_BUILD_DIR/:/documents/
    --name asciidoc-to-html 
    asciidoctor/docker-asciidoctor
    asciidoctor-revealjs
    -a revealjsdir=reveal.js
    -r asciidoctor-diagram
    -o index.html
    -D /documents/output
    all_in_one.adoc

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output
  on:
    branch: master  
